### ISSUE TITLE
change.activeDescendant triggers but may not send the active descendant

### ISSUE THREAD

**Issue by sendlo** [ianmcburnie/jquery-active-descendant#1]
"change.activeDescendant" will trigger anytime the "change" event is triggered on the input field, such as pressing enter or pasting content, as default jQuery behavior.  But since it isn't triggered by this plugin the "newActiveDescendant" will be empty.

If the event name wasn't intentional you may want to rename it.  Otherwise you may want to document that the developer should test for the value before reacting to the event.

**Comment by ianmcburnie** [comment]
@sendlo Oh, cack. No this wasn't intentional. I thought that because my `change` event is namespaced it wouldn't fire in these situations. Thank you for finding this! I will have to change the event name. Pretty sure I might have the same issue in other plugins...

**Comment by ianmcburnie** [comment]
So, there was a misunderstanding on my behalf on how jquery event namespaces are used. Will rename 
change.activeDescendant to activeDescendantChange.

**Comment by ianmcburnie** [comment]
Fixed.
